name: vg_stats
description: Compute statistics on graph or alignment files
keywords:
  - statistics
  - pangenome
  - graph
  - vg
tools:
  - vg:
      description: Variation graph toolkit
      homepage: https://github.com/vgteam/vg
      documentation: https://github.com/vgteam/vg/wiki
      licence: ["MIT"]
      identifier: biotools:vg

input:
  - - meta:
        type: map
        description: Sample/graph metadata
    - input_file:
        type: file
        description: Graph or alignment file (VG, GBZ, GAM, GAF)
        pattern: "*.{vg,gbz,gam,gaf}"

output:
  - stats:
      - meta:
          type: map
          description: Sample/graph metadata
      - "*.stats":
          type: file
          description: Statistics output
          pattern: "*.stats"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@jlalli"
maintainers:
  - "@jlalli"
